name: 'Hello World Action by ArianJC2002'
description: 'Greet someone and record the time'
inputs:
  who-to-greet: #id of the input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs: #id of the output
  time:
    description: 'The time we greeted you
runs:
  using: 'node20'
  main: 'index.js'