name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        message: ["Hello", "CodigoFacilito", "Bootcamp GitHub Actions"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Print message
        run: echo "${{ matrix.message }}"