name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["Hello", "CodigoFacilito", "Bootcamp GitHub Actions"]

    steps:
      - name: Print message
        run: echo "${{ matrix.message }}"