name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
      my_variable: ${{ steps.step_1.outputs.my_variable }}
    # This job will run on every push to any branch
    env:
      MY_ENV_VAR: "Hello World"
    steps:
      - name: Generar archivo de log
        id: step_1
        run: |
          echo "Archivo prueba, hola" >> test.log

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log

  second-job:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar artefacto
      uses: actions/download-artifact@v4
      with:
        name: archivo-test
    
    - name: Cat file
      run: cat test.log