name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo desde el primer job"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo desde el segundo job"