name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "Hello World"
    steps:
      - name: Working dir
        run: ls -al
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Working dir after checkout
        run: ls -al

  second-job:
    if: ${{ github.ref == 'refs/heads/main' }} 
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo desde el segundo job"